Learn/Areas/Admin/Controllers/ProductTypeController.cs
using Learn.Data;
using Learn.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Learn.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Route("Admin/[controller]")]
    //[Authorize(Roles = "Admin")]

    public class ProductTypeController : Controller
    {
        private readonly OnlineShopJoyContext _context;

        public ProductTypeController(OnlineShopJoyContext context)
        {
            _context = context;
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(_context.ProductTypes.ToList());
        }

        //AddOrEdit Get Method
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        //AddOrEdit Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Learn.Models.ProductType employeeData)
        {
            if (ModelState.IsValid)
            {
                _context.ProductTypes.Add(employeeData);
                await _context.SaveChangesAsync();
                TempData["save"] = "Product type has been saved";
                return RedirectToAction(nameof(Index));
            }

            return View(employeeData);


            //bool IsEmployeeExist = false;

            //Learn.Models.ProductType employee = await _context.ProductTypes.FindAsync(Id);

            //if (employee != null)
            //{
            //    IsEmployeeExist = true;
            //}
            //else
            //{
            //    employee = new Learn.Models.ProductType();
            //}

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        employee.Id = employeeData.Id;
            //        employee.ProductType1 = employeeData.ProductType1;
            //        //employee.Address = employeeData.Address;
            //        //employee.Salary = employeeData.Salary;
            //        //employee.JoiningDate = employeeData.JoiningDate;

            //        if (IsEmployeeExist)
            //        {
            //            _context.Update(employee);
            //        }
            //        else
            //        {
            //            _context.Add(employee);
            //        }
            //        await _context.SaveChangesAsync();
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        throw;
            //    }
            //    return RedirectToAction(nameof(Index));
            //}
            //return View(employeeData);
        }


        // Employee Details
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var employee = await _context.ProductTypes.FirstOrDefaultAsync(m => m.Id == Id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // GET: Employees/Delete/1
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var employee = await _context.ProductTypes.FirstOrDefaultAsync(m => m.Id == Id);

            return View(employee);
        }

        // POST: Employees/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            var employee = await _context.ProductTypes.FindAsync(Id);
            _context.ProductTypes.Remove(employee);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Learn/Areas/Admin/Views/ProductType/Create.cshtml
@model Learn.Models.ProductType
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container p-3 my-3 border">
    <h1> @ViewBag.PageName</h1>

    <div class="row">
        <div class="col-sm-6">
            <hr />
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             
              @*  <div class="form-group">
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="ProductTypes" class="control-label"></label>
                    <input asp-for="ProductTypes" class="form-control" />
                    <span asp-validation-for="ProductTypes" class="text-danger"></span>
                </div>
             
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Save" />
                    <a class="btn btn-danger" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Pages/Shared/_ValidationScriptsPartial.cshtml");
    }
}

Learn/Areas/Admin/Views/ProductType/Delete.cshtml
@model Learn.Models.ProductType
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deleting Employee</h2>

<h3>Would you like to continue?</h3>
<div class="container p-3 my-3 border">
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ProductTypes)
        </dd>
       
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input class="btn btn-primary" type="submit" value="Yes" />
        <a class="btn btn-danger" asp-action="Index">No</a>
    </form>

</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Pages/Shared/_ValidationScriptsPartial.cshtml");
    }
}

Learn/Areas/Admin/Views/ProductType/Details.cshtml
@model Learn.Models.ProductType
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container p-3 my-3 border">
    <h1>Employee Details</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ProductTypes)
        </dd>

    </dl>
    <div>
        <a class="btn btn-primary" asp-action="AddOrEdit" asp-route-employeeId="@Model.Id">Edit</a>
        <a class="btn btn-danger" asp-action="Index">Back</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Pages/Shared/_ValidationScriptsPartial.cshtml");
    }
}

Learn/Areas/Admin/Views/ProductType/Index.cshtml
@model IEnumerable<Learn.Models.ProductType>
@using Learn.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Product Type List</h1>

<p style="text-align:right;margin-right:20px;">
    <a class="btn btn-outline-primary" asp-action="Create">Create New</a>
</p>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductTypes)
                </th>
                <th></th>
                <th>Edit Action</th>
                <th>Details Action</th>
                <th>Delete Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductTypes)
                    </td>
          
                    <td>
                    <td class="text-center">
                        <a asp-action="Create" class="btn btn-outline-primary" asp-area="Admin" asp-controller="ProductType" asp-route-employeeId="@item.Id">Edit</a>
                    </td>
                    <td class="text-center">
                        <a asp-action="Details" class="btn btn-outline-info" asp-area="Admin" asp-controller="ProductType" asp-route-employeeId="@item.Id">Details</a>
                    </td>
                    <td class="text-center">
                        <a asp-action="Delete" class="btn btn-outline-danger" asp-area="Admin" asp-controller="ProductType" asp-route-employeeId="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            var save = '@TempData["save"]'
            if (save != '') {
                alertify.success(save);
            }
            //var edit = '@TempData["edit"]'
            //if (edit != '') {
            //    alertify.success(edit);
            //}
            //var del = '@TempData["delete"]'
            //if (del != '') {
            //    alertify.error(del);
            //}
        })
    </script>
  
}